# Site settings
title: 未完成
email: vkyii@foxmail.com
url: http://www.vkyii.com
description: 每一次成功,都来之不易.
# 站点信息
rss_url: /pages/atom.xml
# 图床
# img_url: http://7xsutu.com1.z0.glb.clouddn.com
img_url: ../..
# img_url: /assets/img


# Social account
# twitter:  username
# weibo:    ID
# github:   vkyii
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


#多说配置
duoshuo_short_name: vkyii


# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown

kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  
sass:
  style: compressed

avatar: /assets/img/avatar.png
favicon: /assets/img/qrcode.jpg

# <picture>
picture:
  source: "_posts"
  # posts_folders: ":year/:month/:day-:slug/"
  output: "assets/img"
  markup: picture

  presets:
    default:
      ppi: [1, 2]
      source_800:
        media: "(min-width: 800px)"
        width: "800"
      source_640:
        media: "(min-width: 640px)"
        width: "720"
      source_480:
        media: "(min-width: 480px)"
        width: "576"
      source_320:
        media: "(min-width: 320px)"
        width: "432"
      source_default:
        width: "288"
    onehalf:
      attr:
        class: "onehalf"
      ppi: [1, 2]
      source_800:
        media: "(min-width: 800px)"
        width: "432"
      source_640:
        media: "(min-width: 640px)"
        width: "360"
      source_480:
        media: "(min-width: 480px)"
        width: "288"
      source_320:
        media: "(min-width: 320px)"
        width: "216"
      source_default:
        width: "144"
    onethird:
      attr:
        class: "onethird"
      ppi: [1, 2]
      source_640:
        media: "(min-width: 640px)"
        width: "288"
      source_480:
        media: "(min-width: 480px)"
        width: "216"
      source_320:
        media: "(min-width: 320px)"
        width: "144"
      source_default:
        width: "96"
    onefourth:
      attr:
        class: "onefourth"
      ppi: [1, 2]
      source_640:
        media: "(min-width: 640px)"
        width: "216"
      source_480:
        media: "(min-width: 480px)"
        width: "144"
      source_320:
        media: "(min-width: 320px)"
        width: "144"
      source_default:
        width: "96"