# Site settings
title: 未完成
email: vkyii@foxmail.com
url: http://www.vkyii.com
description: 每一次成功,都来之不易.
# 站点信息
rss_url: /pages/atom.xml


# Social account
# twitter:  username
# weibo:    ID
# github:   vkyii
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


#多说配置
duoshuo_short_name: vkyii


# Google Analytics
# google_analytics: tracking_ID


# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
sass:
  style: compressed

avatar: http://i5.tietuku.com/e6751cf5be327342.jpg
favicon: http://i5.tietuku.com/e6751cf5be327342.jpg
